.TH COLORIZE 1 "2019-02-23" "colorize v0.64" "User Commands"
.SH NAME
colorize \- colorize text on terminal with ANSI escape sequences
.SH SYNOPSIS
\fBcolorize\fR [\fIoption\fR]... (\fIforeground\fR) [\fI-|file\fR]
.PP
\fBcolorize\fR [\fIoption\fR]... (\fIforeground\fR)/(\fIbackground\fR) [\fI-|file\fR]
.PP
\fBcolorize\fR \-\-clean[\-all] [\fI-|file\fR]
.PP
\fBcolorize\fR \-hV
.SH DESCRIPTION
Colorizes text read from standard input stream or file by using ANSI
escape sequences (and also vice versa, i.e. cleaning text from sequences)
and prints resulting output to the terminal.
.PP
When colorizing text, (foreground) and eventually (background) may be either
one of following color values: none, black, red, green, yellow, blue, magenta,
cyan, white, default or random.  First character of color name in upper
case denotes increased intensity, whereas for lower case colors will be of
normal intensity.  If "none" is chosen, no escape sequences will be emitted.
.PP
Color escape sequences are added per each line, hence colored lines can be
safely extracted.
.PP
When de-colorizing text, \-\-clean omits color escape sequences which
were emitted by colorize (see NOTES for list), whereas \-\-clean\-all
omits all valid ones.  If in doubt, consider using \-\-clean\-all.
.SH OPTIONS
.TP
.BR \-\-attr=\fIATTR1,ATTR2,...\fR
set attributes by name
.RS
Attributes: bold, underscore, blink, reverse and concealed.
.RE
.TP
.BR \-\-clean
clean text from color escape sequences emitted by colorize
.TP
.BR \-\-clean\-all
clean text from all valid color escape sequences
.TP
.BR \-\-exclude\-random=\fICOLOR\fR
text color to be excluded when selecting a random foreground color
.TP
.BR \-\-omit\-color\-empty
omit printing color escape sequences for empty lines
.TP
.BR \-h ", " \-\-help
show help screen and exit
.TP
.BR \-V ", " \-\-version
display version data and exit
.SH NOTES
The list of color escape sequence codes being emitted and omitted is
as follows:
.IP * 4
30-37,39 (foreground colors)
.IP * 4
1-9;30-37,39 (foreground colors with attributes)
.IP * 4
40-47,49 (background colors)
.IP * 4
0 (reset)
.SH EXAMPLES
.TP
$ \fBcolorize green /etc/motd\fR
Print file /etc/motd with green as foreground color
.TP
$ \fBcolorize green/black /etc/motd\fR
Print file /etc/motd with green as foreground and black as background color
.TP
$ \fBcolorize green /etc/motd | colorize --clean\fR
Print input from stdin with color escape sequences omitted
.TP
$ \fBgit log -1 -p --color | colorize --clean-all\fR
Print input from stdin with all color escape sequences omitted
.TP
$ \fBcolorize --attr=bold green /etc/motd\fR
Print file /etc/motd with bold green as foreground color
.SH AUTHOR
Steven Schubiger <stsc@refcnt.org>
