.TH COLORIZE 1 "2013-06-16" "colorize v0.50" "User Commands"
.SH NAME
colorize \- colorize text with escape sequences
.SH SYNOPSIS
\fBcolorize\fR [option] (foreground) \fIfile\fR
.PP
\fBcolorize\fR [option] (foreground)/(background) \fIfile\fR
.PP
\fBcolorize\fR \-\-clean[\-all] \fIfile\fR
.PP
\fBcolorize\fR \-hv
.SH DESCRIPTION
Colorizes text read from standard input stream or file by using ANSI
escape sequences (and also vice versa, i.e. cleaning text from sequences)
and prints resulting output to the terminal.
.PP
When colorizing text, (foreground) and eventually (background) may be either
one of following color values: none, black, red, green, yellow, blue, cyan,
magenta, white, default or random.  First character of color name in upper
case denotes increased intensity, whereas for lower case colors will be of
normal intensity.  If "none" is chosen, no escape sequences will be emitted.
.PP
Color escape sequences are added per each line, hence colored lines can be
safely extracted.
.PP
When de-colorizing text, \-\-clean omits color escape sequences which
were emitted by colorize, whereas \-\-clean\-all omits all valid ones.
If in doubt, consider using \-\-clean\-all.
.SH OPTIONS
.TP
.BR \-\-clean
clean text from color escape sequences emitted by colorize
.TP
.BR \-\-clean\-all
clean text from all valid color escape sequences
.TP
.BR \-\-exclude\-random=\fICOLOR\fR
text color to be excluded when selecting a random foreground color
.TP
.BR \-h ", " \-\-help
show usage screen and exit
.TP
.BR \-v ", " \-\-version
display version data and exit
.SH AUTHOR
Steven Schubiger <stsc@refcnt.org>
